[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
common = { workspace = true }
env_logger = { workspace = true }
fastrand = { workspace = true }
futures-util = { workspace = true }
jwt-simple = { workspace = true }
log = { workspace = true }
redis = { workspace = true, features = ["connection-manager", "json", "tokio-comp"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha3 = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-macros = { workspace = true }
ureq = { workspace = true, features = ["json"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }

[dev-dependencies]
redis-test = { workspace = true, features = ["aio"] }
serial_test = { workspace = true }
