import numpy as np
from numpy.typing import NDArray

# Type aliases for better readability and performance
BoardState = NDArray[np.int8]  # Shape: (batch, 4, 8, 8) or (4, 8, 8)
ActionProbs = NDArray[np.float32]  # Shape: (batch, 8, 8)
Dones = NDArray[np.bool_]  # Shape: (batch,)

class ReversiEnvironment:
    def __init__(self, batch_size: int, seed: int) -> None: ...
    def clone(self) -> "ReversiEnvironment": ...
    def reset(self) -> BoardState: ...
    def reset_indices(self, indices: list[int]) -> BoardState: ...
    def get_state(self) -> BoardState: ...
    @staticmethod
    def get_next_state(state: BoardState, action: int) -> BoardState: ...
    def step_batch(
        self,
        actions: NDArray,  # Shape: (batch, 8, 8)
        deterministic: bool,
    ) -> tuple[BoardState, Dones]: ...
    @property
    def batch_size(self) -> int: ...
