worker_processes 1;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s;
    server {
        listen 80;
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 "OK";
        }

        # Model endpoint
        location ~ ^/models/(?<model_name>[^/]+)/suggest$ {
            proxy_pass http://$model_name/invocations;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
