on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "server/game/**"

name: build and test (game)

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run build
        run: |
          cargo build
        working-directory: ./server/game
      - name: Run test
        run: |
          cargo test
        working-directory: ./server/game
