on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "app/**"

name: build (app)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run build
        run: |
          npm ci
          npm run build
        working-directory: ./app
