on:
  push:
    branches: [main]
  pull_request:

name: code quality (typos)

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run spellcheck
        uses: crate-ci/typos@master
