on:
  push:
    branches: [main]
  pull_request:
    paths:
      - server/ml/reversi-py/**

name: code quality (reversi-py)

env:
  CARGO_TERM_COLOR: always

jobs:
  format-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run rustfmt
        run: |
          cargo fmt --all --check
        working-directory: ./server/ml/reversi-py

  format-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/ruff-action@v1
        name: Run ruff format
        with:
          args: format --check
          src: ./server/ml/reversi-py

  lint-rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
        working-directory: ./server/ml/reversi-py

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/ruff-action@v1
        name: Run ruff lint
        with:
          args: check
          src: ./server/ml/reversi-py
