on:
  push:
    branches: [main]
  pull_request:
    paths:
      - .github/workflows/code-quality-models.yml
      - server/ml/inference_kit/**
      - server/ml/models/**

name: code quality (models)

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/ruff-action@v1
        name: Run ruff format
        with:
          args: format --check --target-version py39
          src: ./server/ml/inference_kit
          version: "0.16.8"
      - uses: astral-sh/ruff-action@v1
        name: Run ruff format
        with:
          args: format --check --target-version py312
          src: ./server/ml/models
          version: "0.16.8"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/ruff-action@v1
        name: Run ruff lint
        with:
          args: check --target-version py39
          src: ./server/ml/inference_kit
          version: "0.16.8"
      - uses: astral-sh/ruff-action@v1
        name: Run ruff lint
        with:
          args: check --target-version py312
          src: ./server/ml/models
          version: "0.16.8"
