on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/test-models.yml'
      - 'server/ml/inference_kit/**'
      - 'server/ml/models/**'

name: test (models)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [
          'models/lfu_random',
          'models/lfu_tree_self_play',
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Run tests for ${{ matrix.model }}
        working-directory: ./server/ml
        run: |
          cd "${{ matrix.model }}" && uv run pytest
