on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'server/ml/inference_kit/**'
      - 'server/ml/models/**'

name: test (models)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [
          'models/lfu_random',
          'models/lfu_max',
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests for ${{ matrix.model }}
        working-directory: ./server/ml
        run: |
          cd "${{ matrix.model }}" && uv run pytest
