name: test (ml)

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'server/ml/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [
          'models/lfu_random',
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests for ${{ matrix.model }}
        working-directory: ./server/ml
        run: |
          cd "${{ matrix.model }}" && uv run pytest
